name: Publish API package
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # for Creating tags and releases
      issues: write # for Editing issue content, Commenting on issues, Closing issues
      pull-requests: write # for Commenting on PRs, Merging or closing PRs
      id-token: write # for publishing to NPM or JSR
      # packages: write # for publishing to GitHub Packages
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # - name: Run tests
      #  run: npm run test:coverage

      - name: Build the app # just to be sure that it works
        run: npm run build

      - name: Generate OpenAPI Specs
        run: npm run generate:openapi

      - name: Generate package
        run: npm run generate:package

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
